# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proyect
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jossvan/frontend
        ports:
        - containerPort: 4200

---
# Service tipo ClusterIp
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: proyect
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 4200 
      targetPort: 4200
      protocol: TCP
  selector:
    app: frontend