# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc_client
  namespace: proyect
  labels:
    app: grpc_client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc_client
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: grpc_client
    spec:
      containers:
      - name: grpc_client
        image: jossvan/grpcclient
        ports:
        - containerPort: 8000
---
# Service tipo ClusterIp
apiVersion: v1
kind: Service
metadata:
  name: grpcclient-service
  namespace: proyect
  labels:
    app: grpc_client
spec:
  type: ClusterIP
  ports:
    - port: 8000 # escuchando internamente en el cluster
      targetPort: 8000
      protocol: TCP
  selector:
    app: grpc_client
