# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sub
  namespace: proyect
  labels:
    app: redis-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sub
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: redis-sub
    spec:
      containers:
      - name: redis-sub-container
        image: cifgt3/grupo16-redis-sub:v3