# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sub
  namespace: proyect
  labels:
    app: redis-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sub
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: redis-sub
    spec:
      containers:
      - name: redis-sub-container
        image: cifgt3/grupo16-redis-sub:v1
        # no tiene puertos
        ports:
        - containerPort: 3001
---
# Service tipo ClusterIp
apiVersion: v1
kind: Service
metadata:
  name: redis-sub-service
  namespace: proyect
  labels:
    app: redis-sub
spec:
  type: ClusterIP
  ports:
    - port: 3001 # escuchando internamente en el cluster
      targetPort: 3001
      protocol: TCP
  selector:
    app: redis-pub