apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: function-split
  namespace: proyect
spec:
  # The root service that clients use to connect to the destination application.
  service: dummy
  # Services inside the namespace with their own selectors, endpoints and configuration.
  backends:
  - service: grpcclient-service
    weight: 50
  - service: redis-pub-service
    weight: 50